from .tone import SEMITONE


PERFECT_UNISON = 0
MINOR_SECOND = SEMITONE
MAJOR_SECOND = 2 * SEMITONE
MINOR_THIRD = 3 * SEMITONE
MAJOR_THIRD = 4 * SEMITONE
PERFECT_FOURTH = 5 * SEMITONE
PERFECT_FIFTH = 7 * SEMITONE
MINOR_SIXTH = 8 * SEMITONE
MAJOR_SIXTH = 9 * SEMITONE
MINOR_SEVENTH = 10 * SEMITONE
MAJOR_SEVENTH = 11 * SEMITONE
PERFECT_OCTAVE = 12 * SEMITONE


# Some hacks to redefine things.
DIMINISHED_SECOND = PERFECT_UNISON
AUGMENTED_UNISON = MINOR_SECOND
DIMINISHED_THIRD = MAJOR_SECOND
AUGMENTED_SECOND = MINOR_THIRD
DIMINISHED_FOURTH = MAJOR_THIRD
AUGMENTED_THIRD = PERFECT_FOURTH

DIMINISHED_FIFTH = AUGMENTED_FOURTH = 8 * SEMITONE
TRITONE = DIMINISHED_FIFTH

DIMINISHED_SIXTH = PERFECT_FIFTH
AUGMENTED_FIFTH = MINOR_SIXTH
DIMINISHED_SEVENTH = MAJOR_SIXTH
AUGMENTED_SIXTH = MINOR_SEVENTH
DIMINISHED_OCTAVE = MAJOR_SEVENTH
AUGMENTED_SEVENTH = PERFECT_OCTAVE
